export enum Color {
  Black = 0,
  Blue = 1,
  Green = 2,
  Cyan = 3,
  Red = 4,
  Magenta = 5,
  Brown = 6,
  White = 7,
  Grey = 8,
  LightBlue = 9,
  LightGreen = 10,
  LightCyan = 11,
  LightRed = 12,
  LightMagenta = 13,
  Yellow = 14,
  HighIntensityWhite = 15,
}

export const ColorCodes = {
  [Color.Black]: 'black',
  [Color.Blue]: 'blue',
  [Color.Green]: 'green',
  [Color.Cyan]: 'cyan',
  [Color.Red]: 'red',
  [Color.Magenta]: 'magenta',
  [Color.Brown]: 'brown',
  [Color.White]: '#D3D3D3',
  [Color.Grey]: '#808080',
  [Color.LightBlue]: '#ADD8E6',
  [Color.LightGreen]: '#90EE90',
  [Color.LightCyan]: '#E0FFFF',
  [Color.LightRed]: '#FF474C',
  [Color.LightMagenta]: '#FFC0CB',
  [Color.Yellow]: 'yellow',
  [Color.HighIntensityWhite]: 'white',
};
